## Model config
audio_feat_dim: 157         # Audio data len / n_fft (512)
audio_len: 48000
batch_size: 8
net_dim: [157, 157, 157]
integration_layer: 1
dropout_rate: 0.0
max_n_epochs: 50
n_earlystop_epochs: 5
p_train: 0.8
p_test: 0.2

#### Optimizer config
optimizer_type: adam
starter_learning_rate: 0.001
lr_decay: 1.0
l2: 0.0