## Model config
audio_feat_dim: 417         # audio_len / hop_length
audio_len: 80000
batch_size: 8
net_dim: [417, 1024, 1024]    # They used 250 since audio_len was 3s, 48000 samples / 192 (ours is 5s, 80000)
integration_layer: 1
dropout_rate: 0.0
max_n_epochs: 50
n_earlystop_epochs: 5
p_train: 0.8
p_test: 0.2

#### Optimizer config
optimizer_type: adam
starter_learning_rate: 0.001
lr_decay: 1.0
l2: 0.0

### Pre-Processing config
n_fft: 512
hann_win_length: 384
hop_length: 192