## CHANGE THESE VALUES - They are from the Audio-Visual paper 
audio_feat_dim: 250
audio_len: 48000
batch_size: 8
net_dim: [250, 250, 250]
integration_layer: 1
dropout_rate: 0.0
max_n_epochs: 50
n_earlystop_epochs: 5

#### Optimizer config
optimizer_type: adam
starter_learning_rate: 0.001
lr_decay: 1.0
l2: 0.0